<?php namespace VTSThemeOptions;

class OptionsPage{
    public function __construct(){
        if (function_exists('acf_add_options_page')){
            $this->setupOptions();
        }

        if(function_exists('acf_add_local_field_group')){
            $this->setupFields();
        }
    }

    protected function setupOptions(){
        acf_add_options_page(array(
			'page_title' 	=> 'Theme General Settings',
			'menu_title'	=> 'Theme Settings',
			'menu_slug' 	=> 'theme-general-settings',
			'capability'	=> 'edit_posts',
			'redirect'		=> false
		));
    }

    
	
	protected function setupFields(){
        acf_add_local_field_group(array (
			'key' => 'group_587e29db3815c',
			'title' => 'Theme Settings',
			'fields' => array (
				array (
					'placement' => 'left',
					'endpoint' => 0,
					'key' => 'field_587e2a031cc37',
					'label' => 'General',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 5,
					'key' => 'field_587e2aa4509fb',
					'label' => 'Tracking Code',
					'name' => 'tracking_code',
					'type' => 'textarea',
					'instructions' => 'Add code after the < head > tag.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 5,
					'key' => 'field_587e2aff70e94',
					'label' => 'Space before < / head >',
					'name' => 'space_before_head',
					'type' => 'textarea',
					'instructions' => 'Add code before the < / head > tag',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 5,
					'key' => 'field_587e2b1370e95',
					'label' => 'Space after < body >',
					'name' => 'space_afterbody',
					'type' => 'textarea',
					'instructions' => 'Add code after the < body > tag.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 5,
					'key' => 'field_587e2b4170e96',
					'label' => 'Space before < / body >',
					'name' => 'space_before_body',
					'type' => 'textarea',
					'instructions' => 'Add code before the < / body > tag.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
			        'key' => 'field_594c14cf02bd9',
			        'label' => 'Static Telephone',
			        'name' => 'static_phone',
			        'type' => 'text',
			        'instructions' => 'Insert a static Phone Number to be used in shortcode [FIXED_PHONE_NUMBER phone="#-(###)-###-####"]',
			        'required' => 0,
			        'conditional_logic' => 0,
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'default_value' => '1-800-320-9929',
			        'placeholder' => '',
			        'prepend' => '',
			        'append' => '',
			        'maxlength' => '',
		        ),
				array (
					'placement' => 'left',
					'endpoint' => 0,
					'key' => 'field_587e2dcb8f01e',
					'label' => 'Social Media',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
                array (
			        'key' => 'field_594ac220ab5b8',
			        'label' => 'Social Links',
			        'name' => 'social_links',
			        'type' => 'flexible_content',
			        'instructions' => '',
			        'required' => 0,
			        'conditional_logic' => 0,
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'button_label' => 'Add Social Link',
			        'min' => '',
			        'max' => '',
			        'layouts' => array (
				        array (
					        'key' => '594ac22c2842e',
					        'name' => 'social_links_facebook',
					        'label' => 'Facebook',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac250ab5b9',
							        'label' => 'Facebook Link',
							        'name' => 'social_links_facebook_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the Facebook icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
				        array (
					        'key' => '594ac270ab5ba',
					        'name' => 'social_links_twitter',
					        'label' => 'Twitter',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac27cab5bb',
							        'label' => 'Twitter Link',
							        'name' => 'social_links_twitter_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the Twitter icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
				        array (
					        'key' => '594ac4273e602',
					        'name' => 'social_links_youtube',
					        'label' => 'Youtube',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac4483e603',
							        'label' => 'Youtube Link',
							        'name' => 'social_links_youtube_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the Youtube icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
				        array (
					        'key' => '594ac4993e604',
					        'name' => 'social_links_linkedin',
					        'label' => 'LinkedIn',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac4a93e605',
							        'label' => 'Linkedin Link',
							        'name' => 'social_links_linkedin_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the LinkedIn icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
				        array (
					        'key' => '594ac4cf3e606',
					        'name' => 'social_links_pinterest',
					        'label' => 'Pinterest',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac4e23e607',
							        'label' => 'Pinterest Link',
							        'name' => 'social_links_pinterest_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the Pinterest icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
				        array (
					        'key' => '594ac4fe3e608',
					        'name' => 'social_links_google',
					        'label' => 'Google+',
					        'display' => 'block',
					        'sub_fields' => array (
						        array (
							        'key' => 'field_594ac5103e609',
							        'label' => 'Google+ Link',
							        'name' => 'social_links_google_link',
							        'type' => 'text',
							        'instructions' => 'Insert your custom link to show the Google+ icon.',
							        'required' => 1,
							        'conditional_logic' => 0,
							        'wrapper' => array (
								        'width' => '',
								        'class' => '',
								        'id' => '',
							        ),
							        'default_value' => '',
							        'placeholder' => '',
							        'prepend' => '',
							        'append' => '',
							        'maxlength' => '',
						        ),
					        ),
					        'min' => '',
					        'max' => '1',
				        ),
			        ),
		        ),				
				array (
					'placement' => 'left',
					'endpoint' => 0,
					'key' => 'field_587e3519cbb15',
					'label' => 'Header',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'key' => 'field_587e3552cbb16',
					'label' => 'Logo',
					'name' => 'logo',
					'type' => 'image',
					'instructions' => 'Select an image file for your logo.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
                array (
			        'key' => 'field_594c14cf02bd8',
			        'label' => 'Call Text',
			        'name' => 'call_text',
			        'type' => 'text',
			        'instructions' => '',
			        'required' => 0,
			        'conditional_logic' => 0,
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'default_value' => 'Call Now',
			        'placeholder' => '',
			        'prepend' => '',
			        'append' => '',
			        'maxlength' => '',
		        ),
		        array (
			        'key' => 'field_594c14e302bd9',
			        'label' => 'Call Slogan',
			        'name' => 'call_slogan',
			        'type' => 'text',
			        'instructions' => '',
			        'required' => 0,
			        'conditional_logic' => 0,
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'default_value' => 'Not a Loan Company',
			        'placeholder' => '',
			        'prepend' => '',
			        'append' => '',
			        'maxlength' => '',
		        ),
                array (
			        'key' => 'field_594c165e8668e',
			        'label' => 'Hide Ticker?',
			        'name' => 'hide_ticker',
			        'type' => 'true_false',
			        'instructions' => '',
			        'required' => 0,
			        'conditional_logic' => 0,
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'message' => '',
			        'default_value' => 0,
			        'ui' => 1,
			        'ui_on_text' => '',
			        'ui_off_text' => '',
		        ),
		        array (
			        'key' => 'field_594c16788668f',
			        'label' => 'Ticker Custom Message',
			        'name' => 'ticker_custom_message',
			        'type' => 'text',
			        'instructions' => '',
			        'required' => 0,
			        'conditional_logic' => array (
				        array (
					        array (
						        'field' => 'field_594c165e8668e',
						        'operator' => '==',
						        'value' => '1',
					        ),
				        ),
			        ),
			        'wrapper' => array (
				        'width' => '',
				        'class' => '',
				        'id' => '',
			        ),
			        'default_value' => '',
			        'placeholder' => '',
			        'prepend' => '',
			        'append' => '',
			        'maxlength' => 50,
		        ),
				array (
					'placement' => 'left',
					'endpoint' => 0,
					'key' => 'field_587e358ac21cc',
					'label' => 'Footer',
					'name' => '',
					'type' => 'tab',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				array (
					'default_value' => '',
					'new_lines' => 'br',
					'maxlength' => '',
					'placeholder' => '',
					'rows' => 5,
					'key' => 'field_587e35a2c21cd',
					'label' => 'Copyright Bar',
					'name' => 'copyright_bar',
					'type' => 'textarea',
					'instructions' => 'Enter the text that displays in the copyright bar. HTML markup can be used.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
				),
				
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'theme-general-settings',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => '',
			'active' => 1,
			'description' => '',
		));
    }
}