const translations = {
    en : {
        calculatorTitle: 'Loan Calculator',
        amountLabel: 'Amount',
        amountHelpText: 'This is the total amount you wish to borrow.',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        totalPrincipalPaid: 'Total Principal Paid',
        totalInterestPaid: 'Total Interest Paid',
        principalPaid: 'Principal paid',
        interestPaid: 'Interest paid',
        monthYearText: 'Month/Year',
        interestHelpText: 'This is the annual interest rate of your loan; it’s should be defined in your loan agreement.',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        monthlyPayments: 'Monthly Payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        biweeklyLowerText: "bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Loan term in years',
        termInMonths: 'or months',
        orText: 'Or',
        dateHelpText: 'The term of a loan is the amount of time you have to pay it off in full. Please choose a term in either years or months.',
        startDateText: 'Start Date',
        startDateHelpText: 'This is the date you will receive your funds. Payments usually begin the month after the start date.',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        estimatedPayoffDate: 'Estimated Payoff Date',
        amortizationSchedule: 'Amortization Schedule',
        startingDateEmptyText: 'There is no starting date selected.',
        selectDatePlaceholder: 'Click to select a date',
        fullMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        showAmortizationBtnText: 'Show Amortization Schedule',
        hideAmortizationBtnText: 'Hide Amortization Schedule',
        withExtraPayments: 'With extra payments',
        withoutExtraPayments: 'Without extra payments',
        showExtraPayments: 'Add Extra Payments',
        hideExtraPayments: 'Hide Extra Payments',
        extraPaymentsText1: 'Enter an amount on one of the options below and click “Add Extra Payments” to see how it will change the monthly payment, interest paid and total cost of your loan.',
        extraPaymentHelp1: 'Add a set amount of money that you will add to your monthly payment every month.',
        extraPaymentHelp2: 'Make one extra payment every year on a set month.',
        extraPaymentHelp3: 'Make a one-time extra payment on a designated month and year',
        extraPaymentLabel1: 'add to your monthly payment',
        extraPaymentLabel2: 'as an extra annual payment every:',
        extraPaymentLabel3: 'as a one-time extra payment in:',
        addExtraBtnTitle: 'Add Extra Payments',
        extraLumpError: 'Extra payment cannot be made before the current date.',
        dateHelpMessage: '*Please enter a date as: mm/dd/yyyy',
        amortizationTableHelp: 'This table summarizes the repayment schedule of a loan, including dividing the monthly payment between principal and interest charges, total interest paid and the balance of the loan after each payment.',
    },
    es : {
        calculatorTitle: 'Calculadora de Préstamos',
        amountLabel: 'Monto',
        amountHelpText: 'Es la cantidad total que desea tomar prestada.',
        monthlyDepositLabel: 'Depósito Mensual',
        balance: 'Balance',
        interest: 'Interés',
        totalPrincipalPaid: 'Total del monto principal pagado',
        totalInterestPaid: 'Total del interés pagado',
        principalPaid: 'Principal',
        interestPaid: 'Interés pagado',
        monthYearText: 'Mes/Año',
        interestHelpText: 'Es la tasa de interés anual de su préstamo, que debe ser definida en el contrato del préstamo.',
        payments: 'Pagos',
        paymentSingular: 'Pago',
        paymentLower: 'pagos',
        monthlyPayments: 'Pagos mensuales',
        interestLabel: 'Tasa de interés',
        monthly: 'mensual',
        yearText: 'año',
        yearPluralText: 'años',
        yearPluralTextCaipal: 'Años',
        TimeToRepayText: 'Tiempo para pagar',
        totalInterestText: 'Interés total',
        monthlyText: 'Mensual',
        anuallyText: 'Anual',
        biweeklyText: "Quincenal",
        loanAmount: 'Monto del préstamo',
        termInYears: 'Término en años',
        termInMonths: 'o meses',
        orText: 'O',
        dateHelpText: 'El término de un préstamo es la cantidad de tiempo que usted tendrá para pagar el total del monto. Por favor escoja un término en años o meses.',
        startDateText: 'Fecha de Comienzo',
        startDateHelpText: 'Es la fecha en que usted recibirá el dinero prestado. Usualmente los pagos comienzan el mes siguiente luego de la fecha de comienzo.',
        moneyFieldError: 'Use números positivos menores que 1 millón.',
        percentageFieldError: 'Use números positivos menores que 100',
        yearsError: 'Use una cantidad real de años. No se permiten puntos.',
        monthsError: 'Use una cantidad real de meses (menos de 1200).',
        timeError: 'Use un número real de años o meses (años <100 | meses <1200).',
        estimatedPayoffDate: 'Fecha Estimada de su Pago Final',
        amortizationSchedule: 'Plan de amortización',
        startingDateEmptyText: 'No hay una fecha de inicio seleccionada.',
        selectDatePlaceholder: 'Seleccione una fecha',
        fullMonths: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        shortMonths: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        showAmortizationBtnText: 'Ver tabla de amortización',
        hideAmortizationBtnText: 'Ocultar tabla de amortización',
        withExtraPayments: 'Con pagos extras',
        withoutExtraPayments: 'Sin pagos extras',
        showExtraPayments: 'Añadir Pagos Adicionales',
        hideExtraPayments: 'Ocultar Pagos Extras',
        extraPaymentsText1: 'Ingrese la cantidad en una de las alternativas abajo, luego haga click en “Añadir Pagos Adicionales” para ver cómo cambia su pago mensual, el interés pagado y el costo total de su préstamo.',
        extraPaymentHelp1: 'Añadir una cantidad de dinero determinada a su pago mensual.',
        extraPaymentHelp2: 'Hacer un pago adicional cada año, en un mes determinado.',
        extraPaymentHelp3: 'Hacer un pago adicional por única vez en un mes y año determinados.',
        extraPaymentLabel1: 'añadir a su pago mensual',
        extraPaymentLabel2: 'como un pago anual extra cada:',
        extraPaymentLabel3: 'como un pago único extra en:',
        addExtraBtnTitle: 'Adicionar pagos extras',
        extraLumpError: 'El pago adicional no puede hacerse antes de la fecha actual.',
        dateHelpMessage: '*Por favor ingrese la fecha en formato mm/dd/año (el año debe tener cuatro dígitos)',
        amortizationTableHelp: 'Esta tabla resume el plan de pagos de un préstamo, incluyendo el desglose del pago mensual entre el balance principal y los cargos por interés, el interés total pagado y el balance del préstamo luego de cada pago.',
    },
    ca : {
        calculatorTitle: 'Loan Calculator',
        amountLabel: 'Amount',
        amountHelpText: 'This is the total amount you wish to borrow.',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        totalPrincipalPaid: 'Total Principal Paid',
        totalInterestPaid: 'Total Interest Paid',
        principalPaid: 'Principal paid',
        interestPaid: 'Interest paid',
        monthYearText: 'Month/Year',
        interestHelpText: 'This is the annual interest rate of your loan; it’s should be defined in your loan agreement.',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        monthlyPayments: 'Monthly Payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Loan term in years',
        termInMonths: 'or months',
        orText: 'Or',
        dateHelpText: 'The term of a loan is the amount of time you have to pay it off in full. Please choose a term in either years or months.',
        startDateText: 'Start Date',
        startDateHelpText: 'This is the date you will receive your funds. Payments usually begin the month after the start date.',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        estimatedPayoffDate: 'Estimated Payoff Date',
        amortizationSchedule: 'Amortization Schedule',
        startingDateEmptyText: 'There is no starting date selected.',
        selectDatePlaceholder: 'Click to select a date',
        fullMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        showAmortizationBtnText: 'Show Amortization Schedule',
        hideAmortizationBtnText: 'Hide Amortization Schedule',
        withExtraPayments: 'With extra payments',
        withoutExtraPayments: 'Without extra payments',
        showExtraPayments: 'Add Extra Payments',
        hideExtraPayments: 'Hide Extra Payments',
        extraPaymentsText1: 'Enter an amount on one of the options below and click “Add Extra Payments” to see how it will change the monthly payment, interest paid and total cost of your loan.',
        extraPaymentHelp1: 'Add a set amount of money that you will add to your monthly payment every month.',
        extraPaymentHelp2: 'Make one extra payment every year on a set month.',
        extraPaymentHelp3: 'Make a one-time extra payment on a designated month and year',
        extraPaymentLabel1: 'add to your monthly payment',
        extraPaymentLabel2: 'as an extra annual payment every:',
        extraPaymentLabel3: 'as a one-time extra payment in:',
        addExtraBtnTitle: 'Add Extra Payments',
        extraLumpError: 'Extra payment cannot be made before the current date.',
        dateHelpMessage: '*Please enter a Date as: mm/dd/yyyy',
        amortizationTableHelp: 'This table summarizes the repayment schedule of a loan, including dividing the monthly payment between principal and interest charges, total interest paid and the balance of the loan after each payment.',
    },
    fr : {
        calculatorTitle: 'Calculateur de prêt',
        amountLabel: 'Montant',
        amountHelpText: 'Il s’agit du montant total que vous souhaitez emprunter.',
        monthlyDepositLabel: 'Dépôt mensuel',
        balance: 'Solde',
        interest: 'Intérêts',
        totalPrincipalPaid: 'Total du capital payé',
        totalInterestPaid: 'Total des intérêts versés',
        principalPaid: 'Principal payé',
        interestPaid: 'Intérêts payés',
        monthYearText: 'Mois/Année',
        interestHelpText: 'Il s’agit du taux d’intérêt annuel de votre prêt; il doit être défini dans votre',
        payments: 'Paiements',
        paymentSingular: 'Paiement',
        paymentLower: 'paiements',
        monthlyPayments: 'Paiements mensuels',
        interestLabel: 'Taux d’intérêt',
        monthly: 'mensuel',
        yearText: 'année',
        yearPluralText: 'années',
        yearPluralTextCaipal: 'Années',
        TimeToRepayText: 'Délai de remboursement',
        totalBalanceText: 'Solde total',
        totalInterestText: 'Total des intérêts',
        monthlyText: 'Mensuel',
        anuallyText: 'Annuel',
        biweeklyText: "Toutes les deux semaines",
        loanAmount: 'Montant du prêt',
        termInYears: 'Durée du prêt en années',
        termInMonths: 'ou mois',
        orText: 'Ou',
        dateHelpText: 'La durée d’un prêt est le temps dont vous disposez pour le rembourser intégralement. Veuillez choisir une durée en années ou en mois.',
        startDateText: 'Date de début',
        startDateHelpText: 'Il s’agit de la date à laquelle vous recevrez vos fonds. Les paiements commencent généralement le mois suivant la date de début.',
        moneyFieldError: 'Utilisez des chiffres positifs inférieurs à 1 million.',
        percentageFieldError: 'Utilisez des chiffres positifs inférieurs à 100.',
        yearsError: 'Utilisez un nombre réel d’années (inférieur à 100).',
        monthsError: 'Utilisez un nombre réel de mois (inférieur à 1 200).',
        timeError: 'Utilisez un nombre réel d’années et de mois (1 < années < 100 | 12 < mois < 1 200).',
        estimatedPayoffDate: 'Date de remboursement estimée',
        amortizationSchedule: 'Tableau d’amortissement',
        startingDateEmptyText: 'Il n’y a pas de date de début sélectionnée.',
        selectDatePlaceholder: 'Cliquez pour sélectionner une date',
        fullMonths: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        shortMonths: ['Janv', 'Fév', 'Mar', 'Avr', 'Mai', 'Juin', 'Jul', 'Août', 'Sept', 'Oct', 'Nov', 'Déc'],
        showAmortizationBtnText: 'Afficher le tableau d’amortissement',
        hideAmortizationBtnText: 'Cacher le tableau d’amortissement',
        withExtraPayments: 'Avec paiements supplémentaires',
        withoutExtraPayments: 'Sans paiements supplémentaires',
        showExtraPayments: 'Ajouter des paiements supplémentaires',
        hideExtraPayments: 'Cacher les paiements supplémentaires',
        extraPaymentsText1: 'Saisissez un montant dans l’une des options ci-dessous et cliquez sur « Ajouter des paiements supplémentaires » pour voir comment cela modifiera le paiement mensuel, les intérêts payés et le coût total de votre prêt.',
        extraPaymentHelp1: 'Ajoutez un montant fixe que vous ajouterez chaque mois à votre paiement mensuel.',
        extraPaymentHelp2: 'Effectuez un paiement supplémentaire chaque année à un mois fixe.',
        extraPaymentHelp3: 'Effectuez un paiement supplémentaire unique pour un mois et une année donnés.',
        extraPaymentLabel1: 'ajouter à votre paiement mensuel',
        extraPaymentLabel2: 'comme paiement annuel supplémentaire chaque :',
        extraPaymentLabel3: 'comme paiement supplémentaire unique en :',
        addExtraBtnTitle: 'Ajouter des paiements supplémentaires',
        extraLumpError: 'Le paiement supplémentaire ne peut être effectué avant la date actuelle.',
        dateHelpMessage: '*Veuillez saisir une date sous la forme : mm/jj/aaaa.',
        amortizationTableHelp: 'Ce tableau résume le calendrier de remboursement d’un prêt, y compris la répartition du paiement mensuel entre le principal et les intérêts, le total des intérêts payés et le solde du prêt après chaque paiement.',
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}